# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, inputs, ... }:
let hostname = config.networking.hostName;
in {
  imports = [
    inputs.disko.nixosModules.disko
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  # Network drivers for initrd SSH unlock
  boot.initrd.kernelModules = [ "r8169" ];  # Realtek - common for AMD boards
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  disko.devices = {
    disk = {
      cobalto = {
        type = "disk";
        device = "/dev/disk/by-id/nvme-WDC_PC_SN520_SDAPNUW-256G-1002_183457800691";
        content = {
          type = "gpt";
          partitions = {
            ESP = {
              priority = 1;
              name = "ESP";
              start = "1M";
              end = "1G";
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
              };
            };
            root = {
              size = "100%";
              content = {
                type = "luks";
                name = "cobalto-root";
                passwordFile = "/run/secrets/luks_passphrase";
                settings = {
                  allowDiscards = true;
                  crypttabExtraOpts = [ "fido2-device=auto" "tpm2-device=auto" ];
                };
                content = {
                  type = "btrfs";
                  extraArgs = [ "-f" ]; # Override existing partition
                  # Subvolumes must set a mountpoint in order to be mounted,
                  # unless their parent is mounted
                  subvolumes = {
                    # Root subvolume for impermanence (will be reset on boot)
                    "/root" = {
                      mountpoint = "/";
                      mountOptions = [ "compress=zstd" "noatime" ];
                    };

                    # Persistent data subvolume
                    "/persist" = {
                      mountpoint = "/nix/persist";
                      mountOptions = [ "compress=zstd" "noatime" ];
                    };

                    # Nix store (persistent)
                    "/nix" = {
                      mountOptions = [ "compress=zstd" "noatime" ];
                      mountpoint = "/nix";
                    };

                    # Swap subvolume
                    "/swap" = {
                      mountpoint = "/.swapvol";
                      swap = { swapfile.size = "36G"; };
                    };
                  };

                  mountpoint = "/partition-root";

                };
              };
            };
          };
        };
      };
      storage = {
        type = "disk";
        device = "/dev/disk/by-id/ata-WDC_WD5000LPVX-22V0TT0_WD-WX71E23XDM75";
        content = {
          type = "gpt";
          partitions = {
            storage = {
              size = "100%";
              content = {
                type = "luks";
                name = "cobalto-storage";
                passwordFile = "/run/secrets/luks_passphrase";
                settings = {
                  allowDiscards = true;
                  crypttabExtraOpts = [ "fido2-device=auto" "tpm2-device=auto" ];
                };
                content = {
                  type = "btrfs";
                  extraArgs = [ "-f" ]; # Override existing partition
                  mountpoint = "/nix/storage";
                  mountOptions = [ "compress=zstd" ];
                };
              };
            };
          };
        };
      };
      media = {
        type = "disk";
        device = "/dev/disk/by-id/ata-ST3000DM001-1CH166_W1F20M0B";
        content = {
          type = "gpt";
          partitions = {
            media = {
              size = "100%";
              content = {
                type = "luks";
                name = "cobalto-media";
                passwordFile = "/run/secrets/luks_passphrase";
                settings = {
                  allowDiscards = true;
                  crypttabExtraOpts = [ "fido2-device=auto" "tpm2-device=auto" ];
                };
                content = {
                  type = "btrfs";
                  extraArgs = [ "-f" ]; # Override existing partition
                  mountpoint = "/mnt/media";
                  mountOptions = [ "compress=zstd" ];
                };
              };
            };
          };
        };
      };
  };

  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault true;
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";

  # SSH Unlocking for LUKS encrypted disks (systemd initrd)
  # Permite desbloquear discos encriptados por SSH durante el arranque
  boot.initrd.network = {
    enable = true;
    ssh = {
      enable = true;
      port = 2222;
      hostKeys = [ "/nix/persist/etc/ssh/ssh_host_ed25519_key" ];
      authorizedKeys = [
        "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBM2hEBu4cWTnBMbGdu2bG+sAZu5kBMtc75NFhShmX21"
      ];
    };
  };

  # Static IP configuration for initrd (systemd stage 1)
  boot.initrd.systemd.network = {
    enable = true;
    networks."10-enp7s0" = {
      matchConfig.Name = "enp7s0";
      networkConfig.DHCP = "no";
      addresses = [
        { Address = "192.168.1.85/24"; }
      ];
      routes = [
        { Gateway = "192.168.1.1"; }
      ];
    };
  };

  # Permitir desbloqueo interactivo en consola
  boot.initrd.luks.devices = {
    "cobalto-root".allowDiscards = true;
    "cobalto-storage".allowDiscards = true;
    "cobalto-media".allowDiscards = true;
  };
}
