# Hardware configuration for rubi
# Disk: nvme1n1 (Kingston SNV2S1000G 1TB) - ONLY this disk is managed
# Debian disk (nvme0n1 Samsung) is NOT touched - only detected by bootloader
{
  config,
  lib,
  pkgs,
  modulesPath,
  inputs,
  ...
}:
let
  hostname = config.networking.hostName;
in
{
  imports = [
    inputs.disko.nixosModules.disko
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Kernel modules for boot
  # Trimmed to NVMe-only hardware: ahci (SATA), usb_storage, usbhid, sd_mod
  # (USB boot) removed since this machine has no SATA drives and never boots
  # from USB.
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "tpm_tis"
    "tpm_crb"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # AMD GPU: load amdgpu in initrd for proper resolution during boot
  hardware.amdgpu.initrd.enable = true;

  # Use zstd for initrd compression: faster decompression than gzip/lz4 at
  # high compression ratios. -19 = max compression, -T0 = use all CPU cores
  # at build time (decompression is always single-threaded at boot).
  boot.initrd.compressor = "zstd";
  boot.initrd.compressorArgs = [
    "-19"
    "-T0"
  ];

  # Disko configuration - ONLY manages nvme1n1 (Kingston)
  # nvme0n1 (Samsung/Debian) is NEVER referenced here
  disko.devices = {
    disk = {
      rubi = {
        type = "disk";
        # Kingston NVMe - the ONLY disk disko will touch
        device = "/dev/disk/by-id/nvme-KINGSTON_SNV2S1000G_50026B778548EA82";
        content = {
          type = "gpt";
          partitions = {
            # EFI System Partition
            ESP = {
              priority = 1;
              name = "ESP";
              start = "1M";
              end = "1G";
              type = "EF00";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = [ "umask=0077" ];
              };
            };
            # Root partition with LUKS + btrfs
            root = {
              size = "100%";
              content = {
                type = "luks";
                name = "rubi-root";
                settings = {
                  allowDiscards = true;
                  # Hardware-backed encryption: TPM2 and FIDO2 support
                  crypttabExtraOpts = [
                    "tpm2-device=auto"
                    "fido2-device=auto"
                  ];
                };
                content = {
                  type = "btrfs";
                  extraArgs = [ "-f" ]; # Override existing partition
                  subvolumes = {
                    # Root subvolume for impermanence (wiped on boot)
                    "/root" = {
                      mountpoint = "/";
                      mountOptions = [
                        "compress=zstd"
                        "noatime"
                      ];
                    };
                    # Blank snapshot for impermanence reset
                    "/root-blank" = {
                      mountpoint = "/.root-blank";
                      mountOptions = [
                        "compress=zstd"
                        "noatime"
                      ];
                    };
                    # Persistent data subvolume
                    "/persist" = {
                      mountpoint = "/nix/persist";
                      mountOptions = [
                        "compress=zstd"
                        "noatime"
                      ];
                    };
                    # Nix store (persistent)
                    "/nix" = {
                      mountpoint = "/nix";
                      mountOptions = [
                        "compress=zstd"
                        "noatime"
                      ];
                    };
                    # Swap subvolume
                    "/swap" = {
                      mountpoint = "/.swapvol";
                      swap = {
                        swapfile.size = "16G";
                      };
                    };
                  };
                  mountpoint = "/partition-root";
                };
              };
            };
          };
        };
      };
    };
  };

  # TPM2 auto-decryption: enroll key after rebuild with:
  # sudo systemd-cryptenroll --tpm2-device=auto /dev/disk/by-id/nvme-KINGSTON_SNV2S1000G_50026B778548EA82-part2
  # LUKS device is auto-generated by disko (see disk content type = "luks")

  # Network and hardware defaults
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # AMD CPU microcode updates
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Power management
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  # Graphics (AMD Radeon 680M integrated)
  hardware.graphics = {
    enable = true;
    # enable32Bit = true;  # Uncomment when nixpkgs i686 issue is fixed
  };
}
